### PR TITLE
Superficial cleanups

### PR DESCRIPTION
**Pull request by drobilla**
Just some cleanups towards making lv2kit tooling/etc more consistent with LV2 itself and related projects, and hopefully provide some support for making the rewrite smoother.

I'm not particularly attached to any of this, feel free to cherry-pick.  There seems to be both a `master` and `main` branch, I based this on `master` because it was already mostly clang-formatted, whereas `main` seems to have massively diverged from the configuration.  Let me know if this should be switched around, or just drop that bit for now.

### CODE REVIEW

**Comment by mfisher31** [comment]
Hey awesome. I was just thinking about clang-tidy the other day.  Thanks.  

So yeah, I changed from master to main as it seems everybody is doing on github these days.  And also added a `develop` branch. Is anything hand written from clang-tidy?  If not I'll cherry pick the tidy files and reformat it all in `develop`.  would be alot easier than fixing all the conflicts.

BTW: this is where I'm headed with all this (plugins and guis in lua too)
https://github.com/lvtk/lvtk/blob/develop/lvtk.lv2/import.lua

I recall a few years back you said GUI's in a nicer language would be cool... welp, time to get serious. C++ <=> Lua class inheritence seems to be working well for the demo.  Alot of binding stuff comes from RND projects over the years and element.

**Comment by mfisher31** [comment]
Oh yeah.  If you actually go to try the demo (readme.md) explains how to run it.   I'll probably crash on startup.  Just keep trying "up button" -> "enter" a few times.    Haven't figured where the exception is thrown even in a try/catch setup or debugger.

Crash never happens when using lvtk.Widget running as a plugin GUI though.  Not sure if it's pugl or lvtk.  will find out soon.

**Comment by drobilla** [comment]
I didn't make any changes based on clang-tidy yet for that reason, although you might need to add a few more suppressions for a different branch or something.  The formatting is just a `ninja clang-format` run, so no work to lose there either.

Cool.  Not much of a lua person personally, but less tedious language options are always good, I'll check it out.

**Comment by mfisher31** [comment]
Yeah, lua is a little weird.  I like it though.  Killer.  I'll merge it all in develop one way or the other.  Really appreciate it!

**Comment by drobilla** [comment]
... hrm.  Gitlab says this was merged into the `develop` branch.  Gitlab, and git, also doesn't seem to think a `develop` branch exists.

What is this black magic?

**Comment by mfisher31** [comment]
Sorry.  I got jumpy on making a develop branch.  Ultimately decided to not go that route and make sure main.

**Comment by mfisher31** [comment]
If you don't mind me asking, what is your mirroring setup from gitlab to github (if any).  I wouldn't mind moving everything there then keep github around for the social aspect.

**Comment by drobilla** [comment]
I use submodules with relative URIs so that things can mirror on whatever host (i.e. be truly decentralized, as git should be).  I don't have anything fancy set up for mirroring, though, I just have all the remotes set up on my dev machine and habitually push to them all manually.

More automation would be nice, but I just have stuff like `for r in origin github; do git push $r; done` in my history so there's not a ton of incentive.  I also merge things manually/locally so I can clean things up without being annoying about nitpicks and such, so working with various remotes is something I'm regularly doing anyway.  So, much like making releases, I'd like some fancy entirely server-side thing to do this, but in practice, it's not that bad to just muddle through manually.

**Comment by mfisher31** [comment]
I like the way you think! lol  Yeah, that's probably the route I take when motivated.

**Pull request merged**
